### PR TITLE
Fix issue #14

### PR DESCRIPTION
**Pull request by etcimon**
Issue referenced by https://github.com/DigitalMars/optlink/issues/14

This old code caused the new CodeView 4 format to be restrained by the limits from the older formats.

### CODE REVIEW

**Comment by WalterBright** [comment]
I'm worried that removing the check causes some overflow elsewhere in the code, leading to memory corruption. On the other hand, it might simply be a vestige of the 16 bit version of the code.

**Comment by WalterBright** [comment]
It's always a bit of an adventure changing anything in Optlink due to the lack of a comprehensive test suite. So we'll have to take a chance.

**Comment by yebblies** [comment]
You could always make it a warning instead of a hard error.  Then at least users would have some indication of where to look if it does produce an invalid/broken exe.

**Comment by WalterBright** [comment]
The near complete lack of an ability to verify I haven't broken things puts an almost intolerable burden on making fixes to Optlink. I have to be extremely careful, which means tedious and time consuming.

**Comment by yebblies** [comment]
Has the optlink download been updated?

**Comment by WalterBright** [comment]
I updated the DMC compiler downloads which include the new optlink.

**Comment by yebblies** [comment]
Thanks, what about `optlink.zip`?

**Comment by WalterBright** [comment]
just uploaded

**Comment by vuaru** [comment]
Ran into this myself today. (timely!)
Replaced dmd's link.exe with the one in the new dmc download.
Seems to work, will let you know if problems crop up. Thanks.

**Comment by WalterBright** [comment]
welcs!

**Pull request merged**
